# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='five',
            field=models.ManyToManyField(related_name='_user_five_+', to='login_app.User'),
        ),
    ]
