# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_user_five'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
