# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_user_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='count',
            new_name='counter',
        ),
    ]
