# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=4)),
                ('driver', models.ManyToManyField(related_name='cars', to='login.User')),
            ],
        ),
    ]
